version: 0.2

phases:
  install:
    commands:
      - su && apt-get update
      - apt-get install sudo
      - sudo -i

      - wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get install -y apt-transport-https
      - sudo apt-get install -y dotnet-sdk-5.0

      - sudo apt-get install software-properties-common
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - nodejs -v
      - npm install -g @angular/cli
      - sudo apt-get install tree

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/VensanguPhotography.ImageApi
      - dotnet tool install -g Amazon.Lambda.Tools
      - dotnet tool update -g Amazon.Lambda.Tools
      - dotnet lambda deploy-function vensangu-api-AspNetCoreFunction-RX0PVYL720XA --function-role "arn:aws:iam::379357806581:role/vensangu-api-AspNetCoreFunctionRole-145L4HJPA1ZX5" --region "us-east-2"

      - cd $CODEBUILD_SRC_DIR/vensangu
      - npm install
      - ng build --prod

artifacts:
  secondary-artifacts:
    VensanguWeb:
      base-directory: '$CODEBUILD_SRC_DIR/vensangu/dist/**'
      files:
        - '*'