version: 0.2

phases:
  install:
    commands:
      - su && apt-get update
      - apt-get install sudo
      - sudo -i

      - wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get install -y apt-transport-https
      - sudo apt-get install -y dotnet-sdk-5.0

      - sudo apt-get install software-properties-common
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - nodejs -v
      - npm install -g @angular/cli
      - sudo apt-get install tree

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/VensanguPhotography.ImageApi
      - dotnet publish --configuration Release

      - cd $CODEBUILD_SRC_DIR/vensangu
      - npm install
      - ng build --prod

artifacts:
  secondary-artifacts:
    VensanguImageApi:
      base-directory: '$CODEBUILD_SRC_DIR/VensanguPhotography.ImageApi/bin/Release/netcoreapp3.1/publish'
      files:
        - '*'
    VensanguWeb:
      base-directory: '$CODEBUILD_SRC_DIR/vensangu/dist/**'
      files:
        - '*'
    